name: zephyr
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - h5py
  - hdf5
  - ipykernel
  - matplotlib
  - networkx
  - notebook
  - numpy
  - pandas
  - pip
  - python=3.11
  - pytz
  - pyyaml
  - scikit-learn
  - scipy
  - tqdm
  - yaml
  - netCDF4
  - bottleneck
  - xarray>=2024.1.0
  - zarr=2.16.*
  - numcodecs>=0.11
  # - dask>=2024.1.0
  - dask
  - fsspec
  - gcsfs
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - pip:
    - hydra-core>=1.3
    - hydra-zen>=0.11
    - omegaconf>=2.3
    - wandb
    - ruff
    - accelerate
    - einops
