name: zephyr
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - hdf5
  - ipykernel
  - matplotlib
  - networkx
  - notebook
  - numpy=1.26.4
  - pandas
  - pip
  - python=3.11
  - pytz
  - pyyaml
  - scikit-learn
  - scipy
  - tqdm
  - yaml
  - netCDF4
  - bottleneck
  - xarray>=2024.1.0
  - zarr=2.16.*
  - numcodecs>=0.11
  - dask>=2024.1.0
  - fsspec
  - gcsfs
  - pip:
    - click==8.1.6
    - cmake==3.27.1
    - docker-pycreds==0.4.0
    - gitdb==4.0.10
    - gitpython==3.1.32
    - lit==16.0.6
    - mccabe==0.7.0
    - mypy-extensions==1.0.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - pathspec==0.11.2
    - pathtools==0.1.2
    - protobuf==4.24.1
    - pycodestyle==2.11.0
    - pyflakes==3.1.0
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - smmap==5.0.0
    - torch==2.0.1
    - torchvision==0.15.2
    - torch_geometric
    - torchmetrics
    - triton==2.0.0
    - hydra-core>=1.3
    - hydra-zen>=0.11
    - omegaconf>=2.3
    - wandb
    - ruff
    - accelerate
    - einops
